package com.cyberassessment.entity;

public enum AuditActivityType {
    AUDIT_CREATED,
    AUDIT_ASSIGNED,
    AUDIT_SENT,
    AUDIT_SUBMITTED,
    AUDIT_COMPLETED,
    AUDIT_ATTESTED,
    ANSWER_SUBMITTED,
    CONTROL_UPDATED,
    FINDING_CREATED,
    FINDING_UPDATED,
    FINDING_RESOLVED,
    FINDING_REMINDER_SENT,
    FINDING_ESCALATED,
    EXCEPTION_REQUESTED,
    EXCEPTION_APPROVED,
    EXCEPTION_REJECTED,
    EXCEPTION_EXPIRED,
    EVIDENCE_ADDED,
    EVIDENCE_REVIEWED,
    EVIDENCE_EXPIRING,
    EVIDENCE_STALE,
    AUDIT_DELETED
}
