package com.cyberassessment.entity;

public enum UserPermission {
    USER_MANAGEMENT,
    APPLICATION_MANAGEMENT,
    AUDIT_MANAGEMENT,
    AUDIT_EXECUTION,
    REPORT_VIEW,
    POLICY_MANAGEMENT,
    COMPLIANCE_MANAGEMENT,
    RISK_MANAGEMENT,
    REMEDIATION_MANAGEMENT
}
