#!/usr/bin/env python3
"""
Groups Kroger CCF controls by base number (KCF_AC-17 <- 17a,17b,...) and emits Flyway SQL
to merge sub-parts into one control row. Run after changing V38 parsing rules if needed.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V38 = ROOT / "backend/src/main/resources/db/migration/V38__kroger_ccf_controls_questions.sql"
OUT = ROOT / "backend/src/main/resources/db/migration/V41__merge_kcf_control_families.sql"


def family_key(cid: str) -> str:
    m = re.match(r"^(KCF_[A-Z]{2,3}-[0-9]+)", cid)
    return m.group(1) if m else cid


def esc(s: str) -> str:
    return s.replace("'", "''")


def main() -> int:
    text = V38.read_text(encoding="utf-8")
    ids = re.findall(
        r"INSERT INTO controls \(control_id, name, description, framework, enabled, category\) VALUES \('([^']+)'",
        text,
    )
    groups: dict[str, list[str]] = defaultdict(list)
    for cid in ids:
        groups[family_key(cid)].append(cid)

    families = {k: sorted(v) for k, v in groups.items() if len(v) > 1}
    if not families:
        print("No multi-part families found", file=sys.stderr)
        return 1

    lines: list[str] = [
        "-- Merge Kroger CCF sub-parts (e.g. AC-17a, AC-17b) into one control per base number (e.g. KCF_AC-17).",
        "-- Generated by scripts/generate_kcf_control_merge_sql.py",
        "",
    ]

    for canonical, members in sorted(families.items(), key=lambda x: x[0]):
        in_list = ",".join(f"'{esc(m)}'" for m in members)
        # Keeper row = MIN(id) among family; matches lexicographically first control_id in V38 seed order.
        keeper_cid = min(members)
        losers = [m for m in members if m != keeper_cid]

        kid = f"(SELECT id FROM controls WHERE control_id = '{esc(keeper_cid)}' AND framework = 'KROGER_CCF')"
        lids = f"(SELECT id FROM controls WHERE control_id IN ({in_list}) AND framework = 'KROGER_CCF')"
        lids_losers = ",".join(f"'{esc(m)}'" for m in losers)
        lids_losers_sql = (
            f"(SELECT id FROM controls WHERE control_id IN ({lids_losers}) AND framework = 'KROGER_CCF')"
            if losers
            else "(SELECT id FROM controls WHERE 1=0)"
        )

        lines.append(f"-- {canonical} <= {', '.join(members)}")
        # 1) Move questions to keeper control PK
        lines.append(
            f"UPDATE questions SET control_id = {kid} WHERE control_id IN {lids} AND control_id <> {kid};"
        )
        # 2) Drop stale mappings for all family controls; reinsert from questions
        lines.append(f"DELETE FROM question_control_mappings WHERE control_id IN {lids};")
        lines.append(
            f"INSERT INTO question_control_mappings (question_id, control_id) SELECT q.id, q.control_id FROM questions q WHERE q.control_id = {kid} "
            f"AND NOT EXISTS (SELECT 1 FROM question_control_mappings m WHERE m.question_id = q.id AND m.control_id = q.control_id);"
        )
        # 3) Governance / other FKs
        for tbl in (
            "questionnaire_template_items",
            "audit_questionnaire_items",
            "requirement_control_mappings",
            "risk_control_links",
        ):
            lines.append(
                f"UPDATE {tbl} SET control_id = {kid} WHERE control_id IN {lids} AND control_id <> {kid};"
            )

        # 4) Audit controls: merge answers onto keeper row, delete duplicate audit_control rows
        if losers:
            # Remove duplicate answers when keeper already answered same question for same audit
            lines.append(
                f"DELETE FROM audit_control_answers WHERE audit_control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_control_answers a2 JOIN audit_controls k ON k.id = a2.audit_control_id AND k.control_id = {kid} JOIN audit_controls l ON l.id = audit_control_answers.audit_control_id AND l.audit_id = k.audit_id WHERE a2.question_id = audit_control_answers.question_id);"
            )
            lines.append(
                f"UPDATE audit_control_answers SET audit_control_id = (SELECT k.id FROM audit_controls k INNER JOIN audit_controls l ON l.id = audit_control_answers.audit_control_id AND l.control_id IN {lids_losers_sql} INNER JOIN audit_controls kk ON kk.audit_id = l.audit_id AND kk.control_id = {kid} WHERE k.id = kk.id) WHERE audit_control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_controls k WHERE k.audit_id = (SELECT audit_id FROM audit_controls WHERE id = audit_control_answers.audit_control_id) AND k.control_id = {kid});"
            )
            # Assignments: point to keeper audit_control or drop if duplicate role
            lines.append(
                f"DELETE FROM audit_control_assignments WHERE audit_control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_control_assignments x WHERE x.audit_control_id IN (SELECT id FROM audit_controls WHERE control_id = {kid}) AND x.user_id = audit_control_assignments.user_id AND x.assignment_role = audit_control_assignments.assignment_role AND audit_control_assignments.audit_control_id IN (SELECT id FROM audit_controls WHERE control_id IN {lids_losers_sql}));"
            )
            lines.append(
                f"UPDATE audit_control_assignments SET audit_control_id = (SELECT k.id FROM audit_controls k JOIN audit_controls l ON l.id = audit_control_assignments.audit_control_id JOIN audit_controls kk ON kk.audit_id = l.audit_id AND kk.control_id = {kid} WHERE k.id = kk.id) WHERE audit_control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_controls k WHERE k.audit_id = (SELECT audit_id FROM audit_controls WHERE id = audit_control_assignments.audit_control_id) AND k.control_id = {kid});"
            )
            for tbl in ("audit_evidences", "findings", "control_exceptions"):
                lines.append(
                    f"UPDATE {tbl} SET audit_control_id = (SELECT k.id FROM audit_controls k JOIN audit_controls l ON l.id = {tbl}.audit_control_id JOIN audit_controls kk ON kk.audit_id = l.audit_id AND kk.control_id = {kid} WHERE k.id = kk.id) WHERE audit_control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_controls k WHERE k.audit_id = (SELECT audit_id FROM audit_controls WHERE id = {tbl}.audit_control_id) AND k.control_id = {kid});"
                )
            lines.append(
                f"DELETE FROM audit_controls WHERE control_id IN {lids_losers_sql} AND EXISTS (SELECT 1 FROM audit_controls k WHERE k.audit_id = audit_controls.audit_id AND k.control_id = {kid});"
            )
            lines.append(
                f"UPDATE audit_controls SET control_id = {kid} WHERE control_id IN {lids_losers_sql};"
            )

        # 5) Canonical id + combined title/description on keeper row
        lines.append(
            f"UPDATE controls SET control_id = '{esc(canonical)}', name = '{esc(canonical.replace('KCF_', ''))}', "
            f"description = (SELECT GROUP_CONCAT(description ORDER BY control_id SEPARATOR ' | ') FROM controls c WHERE c.control_id IN ({in_list}) AND c.framework = 'KROGER_CCF') "
            f"WHERE control_id = '{esc(keeper_cid)}' AND framework = 'KROGER_CCF';"
        )
        lines.append(
            f"DELETE FROM controls WHERE control_id IN ({in_list}) AND framework = 'KROGER_CCF' AND control_id <> '{esc(canonical)}';"
        )
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(families)} families)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
