spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cybersecurity_assessment}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

app:
  evidence-storage-mode: ${EVIDENCE_STORAGE_MODE:db}
